// USD to ZAR exchange rate (approximate)
export const USD_TO_ZAR = 18.5;

export const courses = [
  {
    id: 1,
    title: "Advanced Web Development Mastery Course",
    description: "A 10-week advanced web-development program covering TypeScript, GraphQL, microservices, Docker, CI/CD, cloud deployment, automated testing, monitoring, and large-scale architecture.",
    priceUSD: 2000.00,
    category: "Web Development",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/2f4999616_generated_eb437a0e.png",
    duration: "12 weeks",
    students: 2450,
    rating: 4.9,
    featured: true,
  },
  {
    id: 2,
    title: "Cybersecurity Fundamentals & Threat Defense",
    description: "Master the core principles of cybersecurity including threat analysis, vulnerability assessment, incident response, and building robust defense strategies for modern enterprises.",
    priceUSD: 2800.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/ec45a2222_generated_29b40169.png",
    duration: "14 weeks",
    students: 3120,
    rating: 4.8,
    featured: false,
  },
  {
    id: 3,
    title: "Blockchain Development & Architecture",
    description: "Deep dive into blockchain fundamentals, consensus mechanisms, distributed ledger technology, and building decentralized applications from scratch using modern frameworks.",
    priceUSD: 3300.00,
    category: "Blockchain",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/0e32cfe37_generated_7618056c.png",
    duration: "20 weeks",
    students: 1870,
    rating: 4.7,
    featured: false,
  },
  {
    id: 4,
    title: "Ethical Hacking & Penetration Testing",
    description: "Learn professional penetration testing methodologies, exploit development, social engineering techniques, and how to conduct comprehensive security audits for organizations.",
    priceUSD: 4800.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/9c5ed6ab7_generated_31b41b51.png",
    duration: "18 weeks",
    students: 2780,
    rating: 4.9,
    featured: false,
  },
  {
    id: 5,
    title: "Cloud Security & Infrastructure Protection",
    description: "Comprehensive course on securing cloud environments including AWS, Azure, and GCP. Learn identity management, encryption, compliance frameworks, and zero-trust architecture.",
    priceUSD: 2200.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/befd07007_generated_bfb5f50d.png",
    duration: "12 weeks",
    students: 1540,
    rating: 4.8,
    featured: false,
  },
  {
    id: 6,
    title: "Smart Contracts & DeFi Development",
    description: "Build and deploy smart contracts on Ethereum and Solana. Master Solidity, Web3.js, DeFi protocols, yield farming mechanics, and decentralized exchange architecture.",
    priceUSD: 180.00,
    category: "Blockchain",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/1e0f09ffc_generated_0326c7fa.png",
    duration: "8 weeks",
    students: 1320,
    rating: 4.7,
    featured: false,
  },
  {
    id: 7,
    title: "Network Security & Firewall Management",
    description: "Master network security protocols, firewall configuration, intrusion detection systems, VPN setup, and network monitoring tools used by enterprise security teams worldwide.",
    priceUSD: 350.00,
    category: "Cybersecurity",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/69803f2a8_generated_446c7086.png",
    duration: "10 weeks",
    students: 2100,
    rating: 4.6,
    featured: false,
  },
  {
    id: 8,
    title: "Crypto Trading & Blockchain Investment",
    description: "Learn advanced cryptocurrency trading strategies, technical analysis, portfolio management, risk assessment, and the fundamentals of blockchain-based financial instruments.",
    priceUSD: 800.00,
    category: "Blockchain",
    image: "https://media.base44.com/images/public/6a057b43c92975536478e242/60cfaa183_generated_9eefcf29.png",
    duration: "12 weeks",
    students: 3450,
    rating: 4.8,
    featured: false,
  },
];

export const instructors = [
  {
    name: "Fluent English Hub",
    title: "Premium English Coaching Brand",
    image: "/media/feh-brand.jpg",
    experience: "FEH",
    credentials: [
      "Premium Branding",
      "Lead Funnels",
      "Modern Website",
    ],
    bio:
      "A premium English coaching brand focused on helping professionals and students improve fluency, confidence, and communication skills.",
    highlights: [
      "Luxury educational branding",
      "Modern responsive website",
      "Social media marketing system",
      "Lead generation focused",
    ],
    courses: [
      "English Coaching",
      "Business English",
      "Confidence Training",
      "Fluency Development",
    ],
  },

  {
    name: "Miraculous Munchies",
    title: "Bakery & Treats Brand",
    image: "/media/miraculous-brand.jpg",
    experience: "Bakery",
    credentials: [
      "Brand Identity",
      "Product Marketing",
      "Social Content",
    ],
    bio:
      "A visually engaging bakery and treats brand built with premium promotional content and strong social media presentation.",
    highlights: [
      "Luxury product visuals",
      "Social media promotions",
      "Modern branding identity",
      "Business growth positioning",
    ],
    courses: [
      "Bakery Branding",
      "Product Advertising",
      "Facebook Promotions",
      "Business Identity",
    ],
  },

  {
    name: "Cavaro Studio",
    title: "Premium Digital Agency",
    image: "/media/cavaro-brand.jpg",
    experience: "Agency",
    credentials: [
      "Web Design",
      "IT Support",
      "Business Growth",
    ],
    bio:
      "A premium web design and IT solutions brand helping businesses improve trust, appearance, and digital presence.",
    highlights: [
      "Luxury website experiences",
      "Modern IT solutions",
      "Business growth systems",
      "Premium client positioning",
    ],
    courses: [
      "Premium Websites",
      "IT Support",
      "Business Systems",
      "Brand Growth",
    ],
  },
];

export const testimonials = [
  {
    name: "Marcus Williams",
    role: "Security Analyst",
    text: "The cybersecurity course completely transformed my understanding of network security. The practical exercises were invaluable.",
    avatar: "MW",
  },
  {
    name: "Elena Rodriguez",
    role: "Blockchain Developer",
    text: "Outstanding blockchain investment strategies course. I've successfully applied the techniques and seen great results in my portfolio.",
    avatar: "ER",
  },
  {
    name: "James Thompson",
    role: "IT Manager",
    text: "Excellent content and presentation. The instructors are clearly experts in their field and explain complex concepts very well.",
    avatar: "JT",
  },
];